version: "3.7"
services:
  raspi-finance-react:
    image: example-react
    hostname: example-react
    container_name: example-react
    restart: always
    build:
      context: ./
      args:
        - TIMEZONE=America/Chicago
      dockerfile: Dockerfile
    ports:
      - "3000:443"
